---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
dockitems_persist: []
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - azure-cli
  - bash-completion
  - bat
  - chezmoi
  - dog
  - fish
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - jq
  - lazygit
  - nmap
  - openssl
  - ssh-copy-id
  - readline
  - starship
  - tfenv
  - tgenv
  - tmux
  - wget
  - yq
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - alfred
  - chromedriver
  - docker
  - font-fira-code
  - font-hack-nerd-font
  - iterm2
  - google-chrome
  - microsoft-office
  - slack
  - telegram
  - vagrant
  - visual-studio-code
  - whatsapp

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
